### ISSUE TITLE
各種棒グラフの日別表示時の数値の下に日付を表示

### ISSUE THREAD

**Issue by aktnk** [aktnk/covid19#1]
## 改善詳細 / Details of Improvement
- 累計表示時に日付が表示されるように、日別表示時にも日付を表示する

## スクリーンショット / Screenshot

‐ 現状
![wo_date1](https://user-images.githubusercontent.com/13390370/79690067-85834f00-8293-11ea-9048-c081a109f4cd.PNG)
![wo_date2](https://user-images.githubusercontent.com/13390370/79690073-8caa5d00-8293-11ea-9390-7914e1e2b464.PNG)
![wo_date3](https://user-images.githubusercontent.com/13390370/79690078-916f1100-8293-11ea-958a-11baec95b558.PNG)

## 期待する見せ方・挙動 / Expected behavior
- ”実績値”⇒”〇/〇 実績値”と日付を表示する
下のように東京都は日付が入っている
![w_date_metro](https://user-images.githubusercontent.com/13390370/79690154-ef035d80-8293-11ea-817b-33466ac05ac7.PNG)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
下記で修正を実施し、プルリクエストを行った。https://github.com/aktnk/covid19/tree/feature/aktnk-issue%231-add-date-in-graph-index

**Comment by hrsano645** [comment]
GitHub Actionsでビルドエラー出ちゃってますね。東京都からの取り込みのようなのにエラー出ちゃう理由がまだわかってませんが🤔

**Comment by aktnk** [comment]
同じコードを手打ちで入力したため、改行位置が違う。
⇒標準スタイルにあっていないため、エラーになってしまったと解釈しました。
元のコミットと同じように改行場所も揃えたら、エラーなくなりました。

**Comment by aktnk** [comment]
本日、https://github.com/hiroyuki-ichikawa/covid19 
のmasterリポに反映されたので、closeします。
