### ISSUE TITLE
PCR検査実施件数のカードの追加

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#17]
## 改善詳細 / Details of Improvement

静岡県の依頼あり

- PCR検査の実施件数が見れるようしてほしい
- データは仮でexcel形式で提供あり

詳細のslack:https://codefornumazu.slack.com/archives/C011YSQPQCA/p1590309611010600

### 対応方法の仮案

メトロ版のグラフカードを追加すればよいはずです。

検査実施件数で検索をしたときの結果はこちらで

https://github.com/tokyo-metropolitan-gov/covid19/search?q=検査実施件数&unscoped_q=検査実施件数

以下を移植する。
- covid19/components/cards/TestedNumberCard.vue 
- covid19/components/TestedCasesDetailsTable.vue

index.vueにカードの追加を行う
- covid19/pages/index.vue

参考として、メトロ版のindex.vueに乗ってるカードの一覧に載せている様子

https://github.com/tokyo-metropolitan-gov/covid19/blob/86844fa4444b4215075cedbe9cb224324828c628/pages/index.vue#L50

### 不明点

- data.jsonの構造がどうなっているかをメトロ版を参考に把握する（[data.json生成スクリプト](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref)側で扱う必要あり）

---

同時にデータ側の対応が必要になるので、[data.json生成スクリプト](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref)のリポジトリにissueを作ります。

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/1

## スクリーンショット / Screenshot

メトロ版の例

![image](https://user-images.githubusercontent.com/23502/83313596-e8341700-a251-11ea-83bd-85bb5567772c.png)

## 期待する見せ方・挙動 / Expected behavior
- メトロ版の「検査実施人数」と同等のグラフを実装する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
下記ブランチに検査実施件数のグラフを追加しました。
https://github.com/aktnk/covid19/tree/feature/aktnk%2317-add-inspections-graph

（はじめに）
・data.jsonは入手したExcelファイルの情報をもとに、inspection_personsと同じ形式で手動作成したものを用いました。

（結果）
・検査実施件数のグラフは、仮に検査実施人数の次に追加しました。
![検査実施件数追加](https://user-images.githubusercontent.com/13390370/83333797-5a057280-a2dd-11ea-977d-3ddf502581a5.PNG)

（動作確認）
・累計のグラフを表示させ、Excelデータの合計と一致することを確認しました。
![検査実施件数累計](https://user-images.githubusercontent.com/13390370/83333817-79040480-a2dd-11ea-9e7b-5b7b3e9cb22a.PNG)
![検査実施件数合計_元データ](https://user-images.githubusercontent.com/13390370/83333818-7d302200-a2dd-11ea-8e5d-56e0b554906d.PNG)
・英語版も日本語等含まれず、表示されることを確認しました。
![検査実施件数英語](https://user-images.githubusercontent.com/13390370/83333877-cc765280-a2dd-11ea-96ac-0c1b4c9c907a.PNG)
・やさしいにほんご版も、平仮名もしくは漢字＋振り仮名で表示されることを確認しました。
![検査実施件数やさしいにほんご](https://user-images.githubusercontent.com/13390370/83333904-f4fe4c80-a2dd-11ea-9a56-1f32e4d01a5f.PNG)
・SNSシェア用コンテンツも正常に表示されること確認しました。
![検査実施件数SNSシェアコンテンツ](https://user-images.githubusercontent.com/13390370/83333922-08a9b300-a2de-11ea-8647-94a9844a8f01.PNG)

**Comment by hrsano645** [comment]
@aktnk お疲れ様です👍
commitログもみましたが、挙動自体のSSでも問題ないと思います。カード自体の追加は修正量も少なくてよさそうですね。この先も必要に応じて増やせそう。
https://github.com/aktnk/covid19/commit/e7435c8f9a38fcb7beff59d19fce947794e55634

**Comment by hrsano645** [comment]
data.jsonの更新はもうちょっとお待ちください。今の進捗はリファクタリングをして新しいデータの追加をしやすくしています。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/3

**Comment by hrsano645** [comment]
このブランチで作業中です
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/issue-1_add_inspections_summary

**Comment by aktnk** [comment]
まだ途中ですが、ご対応ありがとうございます。
data.jsonの生成はとても分かりやすくなりました！
今後ももう暫く続くと思いますが、よろしくお願いします。

そう言えば、issueタイトル内の「検査実施人数」は「検査実施件数」ですね。

**Comment by hrsano645** [comment]
人数→件数ですね。気が付きませんでした😅

**Comment by hrsano645** [comment]
data.jsonの生成スクリプト側の最新のcommitがこちらです。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/9511dd5f06fa5621ec71a3a5b9b494fdb9fdf386

ここまでの変更を元に、 @aktnk さんの 検査実施件数カードの実装したコードを自分のローカル環境で取り込んで、data.json自体が正しく読み込まれるかと、検査実施件数が表示できるか確認してみました。

https://github.com/aktnk/covid19/commit/e7435c8f9a38fcb7beff59d19fce947794e55634

---

全体の表示結果

<img width="1144" alt="スクリーンショット 2020-06-04 11 38 11" src="https://user-images.githubusercontent.com/23502/83709059-b27b9d80-a658-11ea-8448-c79274053cad.png">

<img width="1144" alt="スクリーンショット 2020-06-04 11 38 20" src="https://user-images.githubusercontent.com/23502/83709064-b6a7bb00-a658-11ea-93c1-386ae714864a.png">

<img width="1144" alt="スクリーンショット 2020-06-04 11 38 26" src="https://user-images.githubusercontent.com/23502/83709065-b7405180-a658-11ea-8743-26daeaf308df.png">

---

PCR検査実施件数の表示結果

累計も問題ないことを確認しました。

<img width="579" alt="スクリーンショット 2020-06-04 11 38 42" src="https://user-images.githubusercontent.com/23502/83709089-c2937d00-a658-11ea-8d68-7eed5f3e8487.png">

<img width="579" alt="スクリーンショット 2020-06-04 11 38 50" src="https://user-images.githubusercontent.com/23502/83709117-d2ab5c80-a658-11ea-9cb8-365dd30023a2.png">

**Comment by hrsano645** [comment]
実際に動作させたブランチはこちらです。data.jsonも新しいスクリプトで生成したものに置き換えました。
https://github.com/hrsano645/covid19/commit/c7446748839e3cac65cca6ae19cd0d5ef8abc25c

**Comment by aktnk** [comment]
@hrsano645 さん、良さそうですね！

**Comment by hrsano645** [comment]
ですね👍
あとはオープンデータの提供待ちかな。それに合わせて修正もしますね。

**Comment by aktnk** [comment]
@hrsano645 さん
下記にtypoがありましたので、お知らせしておきます。
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/9511dd5f06fa5621ec71a3a5b9b494fdb9fdf386/patients.py#L177
varidate -> validate

**Comment by hrsano645** [comment]
@aktnk PR出すのでそちらで修正した分を出しますね

**Comment by hrsano645** [comment]
@aktnk PRだしたものがこちらです。修正済みです👍

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/5/commits/1f1ab0e904fb6f7b14c3982212fee585fcc6d117

**Comment by aktnk** [comment]
python使いながら勉強しているのですが、今回のpatients.pyのコードを拝見し、
書いたことがない書き方をしているので、とても刺激になりました。

**Comment by aktnk** [comment]
１）グラフ生成部のコミット
https://github.com/aktnk/covid19/commit/783181f21c5aa7662c638cb209622a3fa0bc9451
２）多言語対応のコミット
https://github.com/aktnk/covid19/commit/4320dcbe8e41e0ffe1c138d3a156b353546aa83f

**Comment by hrsano645** [comment]
@aktnk ありがとうございます！ data.json側も、サイト側に合わせてデータを生成できるようにしますね。
