### ISSUE TITLE
陽性患者の属性の年代が”(空)”とき”代”と表示される

### ISSUE THREAD

**Issue by aktnk** [aktnk/covid19#3]
## 起こっている問題 / The Problem
- 県が公開してい陽性患者の年代が”(空)”となっていると、”代”と表示される。

## スクリーンショット / Screenshot

![代のみ](https://user-images.githubusercontent.com/13390370/79690685-a600d880-8296-11ea-894f-c633ac65e38b.PNG)

## 期待する見せ方・挙動 / Expected Behavior
- 案（１）データが”(空)”のとき”ー”と表示する
- 案（２）データが”(空)”のとき””とする（“代”を表示しない）
- 案（３）データが”(空)”のとき”不明”と表示する（東京都の表示と同じ）
- 案（４）データが”(空)”となっている理由に合わせて、”調査中”、”非公開”と表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 陽性患者の属性にて、4/13 富士宮市のデータを表示すれば常に表示される。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
#2 #4 も同じ部分の問題ですかね？
metro版のほうでも、最新版を見た限りだと、**代の場合は**代として、そのほかはスルーしていました。案2の方法に近いです。

パッチとして変更することは可能のようです。
この部分を移植、置き換えすれば、メトロ版とほぼ同じにできそうです。

https://github.com/tokyo-metropolitan-gov/covid19/blob/28c6b8b86cdbaaef561f941b41a89ec49d9da48d/components/cards/ConfirmedCasesAttributesCard.vue#L58

**Comment by aktnk** [comment]
１）#2,#3,#4とも同じ部分の問題です。

２）ここに記述した案（１）から（４）の後で、下記ルールを整理しました。
なおその際、佐野さんも上げたメトロのConfirmedCasesAttributesCard.vue#L58を前提に考えていました。
https://codefornumazu.slack.com/archives/C011YSQPQCA/p1587989876014200
