### ISSUE TITLE
静岡版はpre-commit.shを外して翻訳jsonファイルの直接ファイルの編集を許可する

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#32]
## 改善詳細 / Details of Improvement

- 静岡版の翻訳はjsonファイルを直接編集しています。
- 現在のコードベースではpre-commit.shで翻訳のjsonファイルの編集が禁止されています
- 回避するために、git comit —no-verify を付ける必要がある

たまにやると忘れてしまうので、静岡版のstopcovid19サイトでは、翻訳はjsonファイルの直接編集にして、pre-commit.sh自体を起動させない（もしくは動かしても何もないようにする）でよいと思います。

## 期待する見せ方・挙動 / Expected behavior
- 翻訳のjsonファイルの編集を行ってcommitをするときに、--no-verifiyオプションをつけなくてもcommit可能にする

対象ファイル: assets/locales/*.json (ja.jsonはpre-commit.shでの編集禁止対象ではありません）

**Comment by aktnk** [comment]
pre-commit.shスクリプト見てみました。
多言語対応のファイルに差分があると、お馴染みのメッセージを出し、エラー終了させていることがわかりました。
現状、静岡版はTransifexを使っていませんので、ご指摘の通り「pre-commit.sh自体を起動させない（もしくは動かしても何もないようにする）」ですね。

**Comment by hrsano645** [comment]
そうですね、今回は明示的にpre-commit.shを動かさないを示すために、pre-commit.sh自体を除去するPR出しておきます。

---
念の為の別の手段として、逆にコードベースをメトロ版からあまりいじりたくない場合は、Transifex自体を使うというのも一つの手で、OSSや非営利は無料で使えます。
https://2020.civictechforum.jp/data/ctf2020/org/speakers.php?mode=movie&id=14

公式ドキュメントはこちら
https://docs.transifex.com/projects/open-source-project

ただ大掛かりな気がしないでもないのと、一度翻訳周りをTransifex側に入れる作業が必要になるかも？
個人的には、この先大きく翻訳の対象名称が増えることはないと思うので、このままでいいかなと。

**Comment by hrsano645** [comment]
pre-commit.sh削除と、husky（package.json>husky）にあるpre-commit.shの実行コマンドを一部消去して、通常のcommit（適当なテキストファイルの追加）と翻訳ファイルのcommit（変更禁止ファイルだったjsonファイルの編集）ができることを確認済みです。

変更内容

https://github.com/hrsano645/covid19/commit/72c001f9ffeed99ea95bcd1d3673d8d94952e16c

通常ファイルcommitの様子

![image](https://user-images.githubusercontent.com/23502/86664672-e2d4a400-c029-11ea-80ea-408bc2709f0c.png)

翻訳ファイルcommitの様子

![image](https://user-images.githubusercontent.com/23502/86664787-fd0e8200-c029-11ea-92f2-33449cf26f65.png)
