### ISSUE TITLE
検査陽性者の状況に、いくつかのデータを追加

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#35]
## 改善詳細 / Details of Improvement
- メトロ版にある「検査陽性者の状況」カードにある、宿泊療養、自宅療養、入院・療養等調整中 の掲載

静岡県の担当の方より連絡
```
サイト中「静岡県内の最新感染動向」のうち、
「検査陽性者の状況」について、
・宿泊療養
・自宅療養
・入院・療養等調整中
以上の３項目の追加をお願いしたいです。
```
イメージは東京都の現在の「検査陽性者の状況」とほぼ同じ

現状ではどういったデータの形式になるかは不明。（ＣSVファイルは前提と思われる？）

カード自体は、メトロ版のコードを移植（パッチ）すれば良いと思われる。内部の構造が変わっていた場合は難易度高そう。

## スクリーンショット / Screenshot

東京都の7/7 19:00更新時の「検査陽性者の状況」カードを参考に掲載。

![image](https://user-images.githubusercontent.com/23502/86865610-4afab700-c10a-11ea-948f-51dca53cdde8.png)

## 期待する見せ方・挙動 / Expected behavior
- メトロ版と同じような「検査陽性者の状況」カードの実装

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
@aktnk さんが試作してくださったブランチはこちら（すごい！！👍

https://github.com/aktnk/covid19/tree/vertical-table

このブランチを引っ張ってきて（適当な手段:git clone/remoteからcheckoutなど）`yarn dev` によるローカル開発環境では動作しているように見えます。バーティカルの表現もメトロ版の通りになっています。

![image](https://user-images.githubusercontent.com/23502/87224877-cfc42a00-c3c3-11ea-8fc7-4c5093c65289.png)

**Comment by aktnk** [comment]
情報の記載ありがとうございます！

**Comment by hrsano645** [comment]
静岡県側の回答の要約です。

> 静岡県側の回答
> 
> ・項目増やして
> ・縦になってもOK
> ・データは案１で
> 
> 大体OKでしたが、公開するデータとして以下に変更してほしい（データの数字も変更。変更はこれでいい？という再質問）
> ・宿泊療養: 2
> ・自宅療養: 3
> ・入院・療養等調整中: 4
> ↓
> ・宿泊療養: 2
> ・入院・療養等調整中: 3

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/9#issuecomment-667075833

**Comment by aktnk** [comment]
今回の要件を満足すべく、下記ブランチに修正を登録しました。
https://github.com/aktnk/covid19/tree/feature/aktnk%2335_add_elements_on_details_of_confirmed_cases
- 今回の変更箇所：検査陽性者の状況
![image](https://user-images.githubusercontent.com/13390370/89101772-25797880-d43e-11ea-903a-4f47d1a1ecaa.png)
- 全体像
![image](https://user-images.githubusercontent.com/13390370/89101744-c156b480-d43d-11ea-969a-b073874fbe05.png)
- 多言語対応：English
![image](https://user-images.githubusercontent.com/13390370/89101783-4d68dc00-d43e-11ea-8038-311d964dd6d0.png)
- 多言語対応：簡体中文
![image](https://user-images.githubusercontent.com/13390370/89101792-62de0600-d43e-11ea-8eee-09fc80459b75.png)
- 多言語対応：繫体中文
![image](https://user-images.githubusercontent.com/13390370/89101855-e697f280-d43e-11ea-8f30-60c519c0697e.png)
- 多言語対応：韓国語
![image](https://user-images.githubusercontent.com/13390370/89101875-0c24fc00-d43f-11ea-8dd9-65a86d149290.png)
- 多言語対応：やさしい日本語
![image](https://user-images.githubusercontent.com/13390370/89101887-22cb5300-d43f-11ea-9d58-7dd3787b1fd6.png)

**Comment by hrsano645** [comment]
こちらのPRで作成したdata.jsonを登録してのチェック 
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/14

---
2020-08-05 09:40 現在のオープンデータで生成したdata.jsonでの結果
現在のデータでは `宿泊療養` `入院・療養等調整中` の記載は無いので0件のまま

<img width="778" alt="スクリーンショット 2020-08-05 9 39 55" src="https://user-images.githubusercontent.com/23502/89359142-0f9ada80-d700-11ea-9a6d-b0e14d0add75.png">

2020-08-05 09:40 現在のオープンデータの末端2行を以下のように編集

No | 全国地方公共団体コード | 都道府県名 | 市区町村名 | 公表_年月日 | 発症_年月日 | 患者_居住地 | 患者_年代 | 患者_性別 | 患者_職業 | 患者_状態 | 患者_症状 | 患者_渡航歴の有無フラグ | 患者_退院済フラグ | 備考
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
320|220001|静岡県|1|2020/8/4||浜松市|20歳未満|女性||軽症・中等症||0|2|
321|220001|静岡県|1|2020/8/4||静岡市葵区|50代|女性|飲食業|軽症・中等症|発熱・咳|0|3|

`宿泊療養` `入院・療養等調整中`はそれぞれ1件づつ現れる。逆に `入院` と `入院 `の子に当たる `軽症・中等症` は２件分減る

<img width="778" alt="スクリーンショット 2020-08-05 9 40 53" src="https://user-images.githubusercontent.com/23502/89359425-c4cd9280-d700-11ea-8e7d-8e3b8ce0b4a5.png">

挙動としては問題ないと思います。
