### ISSUE TITLE
陽性患者の属性の居住地の表記の揺れ（「県外」「県外在住」）

### ISSUE THREAD

**Issue by jandknagaya** [aktnk/covid19#38]
## 起こっている問題 / The Problem
- 陽性患者の属性の居住地の「県外」「県外在住」は同じ意味なのに　表記が違う。

## スクリーンショット / Screenshot
![issu](https://user-images.githubusercontent.com/65159906/88449104-3bf06480-ce7f-11ea-800c-ce17a8de2268.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「県外」に統一

## 起こっている問題の再現手段 / Steps to Reproduce
1. 公開サイト（ https://stopcovid19.code4numazu.org ）を表示する
2. 「陽性患者の属性」をスクロールして居住地を確認する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
表記ゆれについては、生成スクリプト側で対応することになる予定です。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/19
