### ISSUE TITLE
お知らせ欄に注意書きの追加

### ISSUE THREAD

**Issue by jandknagaya** [aktnk/covid19#43]
## 改善詳細 / Details of Improvement
静岡県からの依頼　(市川さんから連絡)
[Slack投稿](https://codefornumazu.slack.com/archives/C011YSQPQCA/p1606291781001800)

## スクリーンショット / Screenshot
![20201125](https://user-images.githubusercontent.com/65159906/100201686-aefc0b80-2f43-11eb-8eab-1c737bb2db2f.PNG)

## 期待する見せ方・挙動 / Expected behavior
お知らせ欄に
「本ページの数字は、公表済みの数字をベースとしているため、実際の入院者数等とは異なる場合があります」を表示する。　　
表示例　↓
![20201125-2](https://user-images.githubusercontent.com/65159906/100202327-83c5ec00-2f44-11eb-8759-6f4b2a38d3b4.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
これ着手します。

**Comment by aktnk** [comment]
修正実施しました。
https://github.com/aktnk/covid19/tree/feature/aktnk-issue%2343-add-warning-message-to-whats-new

下記のようになります。
![2020-11-27_22-30](https://user-images.githubusercontent.com/13390370/100455654-6474bd80-3102-11eb-9ddf-4c0c0cb91403.png)

**Comment by aktnk** [comment]
開発サイト（https://stopcovid19-shizuoka-dev.netlify.app/）にて、期待通りに表示されていることを確認しました。
![image](https://user-images.githubusercontent.com/13390370/100490832-ffe94b00-3161-11eb-83d6-3d7c2d01a77d.png)

次はmasterブランチですね。
