### ISSUE TITLE
検査陽性者の状況カードの元データ（CSV)の変更

### ISSUE THREAD

**Issue by jandknagaya** [aktnk/covid19#44]
## 改善詳細 / Details of Improvement
検査陽性者の状況カードの元データ（CSV)の変更

## スクリーンショット / Screenshot
図のような　CSVファイルから　検査陽性者の状況カードを表示する
![20201125-3](https://user-images.githubusercontent.com/65159906/100203502-07340d00-2f46-11eb-9c06-dd9adc11c1f7.PNG)

## 期待する見せ方・挙動 / Expected behavior
上記のような　CSVファイルから検査陽性者の状況カードの作成

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
CSVで毎回公開される形なら、このファイルをとりこんで検査陽性者の状況のデータ部分を生成するだけで行けそうなので、それほど大変ではなさそうですね。

**Comment by hrsano645** [comment]
確認が必要なことを上げておくと

- 対策サイトの「検査陽性者の状況」の「軽症・中等症」は、CSVファイルの「入院」から「うち重症」を引いた数字となるか
- CSVファイルの「死亡」の数は「退院」の数に入っているか（退院と死亡退院の合計が退院となっているか

**Comment by hrsano645** [comment]
> * 対策サイトの「検査陽性者の状況」の「軽症・中等症」があるが、この数字はCSVファイルの「入院」から「うち重症」を引いた数字で扱っても問題ないか（修正:2020-11-26)

県担当の方に確認したところ、この扱いで問題ないようです。実装はそのままで進めてます。

**Comment by hrsano645** [comment]
生成スクリプト側の対応が終わりました。対策サイト側の #43 のマージが出来たら同時に終了ですね。

**Comment by hrsano645** [comment]
マージ終えたので終了します。お疲れさまでした👍

**Comment by jandknagaya** [comment]
ありがとうございました😊

2020年12月8日(火) 7:18 hiroshi sano <notifications@github.com>:
