### ISSUE TITLE
表示文言変更に伴う多言語対応

### ISSUE THREAD

**Issue by jandknagaya** [aktnk/covid19#45]
## 起こっている問題 / The Problem
issue [#43 ]
の修正に伴う多言語対応

## スクリーンショット / Screenshot
割愛

## 期待する見せ方・挙動 / Expected Behavior
修正に伴う変更は以下のとおり
・「検査実施件数」⇒「検査検体採取実施人数」
・「（注）検査結果の判明日を基準とする」⇒「（注）検体を採取した日を基準とする」
・「地方衛生研究所が行った検査件数」⇒「保健所が行政検査として行った検体採取人数」
・「医療機関等が行った検査件数」⇒「医療機関等が行政検査として行った検体採取人数」
・「本ページの数値は、公表済みの数字をベースとしているため、実際の入院者数等とは異なる場合があります」の追加

## 起こっている問題の再現手段 / Steps to Reproduce
issue [#43 ] の修正後
多言語対応選択メニューで日本語以外を選択する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
ありがとうございます！ 
今のところ、既存のカードの置き換えか、新しくカード追加かどちらかだと思ってますが、翻訳情報をあらかじめ用意しておくとスムーズに対応できそうです👍
