### ISSUE TITLE
「検査陽性者の状況」の個別ページが表示できない

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#47]
## 起こっている問題 / The Problem
- 検査陽性者の状況の個別ページが表示できない
- 404エラーで見られない

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/23502/100529253-e6f79d00-3228-11eb-907e-090d9f010a77.png)

## 期待する見せ方・挙動 / Expected Behavior
- ページを正しく表示できるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. 2020-11-29現在にアクセスすると404エラー
2. アクセス先 -> https://stopcovid19.code4numazu.org/cards/details-of-confirmed-cases

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
開発サイトでは、表示されますね。
![image](https://user-images.githubusercontent.com/13390370/100535350-63a36f00-325b-11eb-9188-6e479881ac78.png)

**Comment by aktnk** [comment]
localhost:3000で確認すると、下記のようなエラーが出てますね。
```covid19 |  ERROR  [Vue warn]: Error in data(): "TypeError: Cannot read property 'date' of undefined"
covid19 | 
covid19 | found in
covid19 | 
covid19 | ---> <Pages/cards/Card.vue> at pages/cards/_card.vue
covid19 |        <Nuxt>
covid19 |          <VApp>
covid19 |            <Layouts/default.vue> at layouts/default.vue
covid19 |              <Root>
covid19 | 
```
![2020-11-29_17-21](https://user-images.githubusercontent.com/13390370/100536953-83d92b00-3267-11eb-86cf-8a8f0a02f9c9.png)

_card.vue の102行目
![2020-11-29_17-24](https://user-images.githubusercontent.com/13390370/100536980-c864c680-3267-11eb-9790-4c6debd9f9f8.png)

data.json　で　inspection_persons.date がない？

**Comment by aktnk** [comment]
data.json ないで"inspection_persons"を検索しても、見つからない・・・なぜ？

**Comment by aktnk** [comment]
- 検査陽性者の状況のカードを作っているConfirmedCasesDetailsCard.vueを確認すると、
`date="Data.patients.date"`となっている。
![2020-11-29_22-19](https://user-images.githubusercontent.com/13390370/100543042-3671b380-3291-11eb-93c3-08ba8997d979.png)

- そこで、_card.vueでエラーの発生している箇所を上記と同じように修正した。
![2020-11-29_22-17](https://user-images.githubusercontent.com/13390370/100543100-82245d00-3291-11eb-9710-d71a2f305aee.png)

- 動作確認すると、正しく表示された。
![2020-11-29_22-17_1](https://user-images.githubusercontent.com/13390370/100543112-95372d00-3291-11eb-9fa9-76c867346640.png)

- ターミナル上にエラーメッセージも表示されなくなった。
（多言語対応の警告メッセージは出ているが・・・）
![2020-11-29_22-18](https://user-images.githubusercontent.com/13390370/100543131-b861dc80-3291-11eb-9db3-e0132e70fee8.png)

**Comment by hrsano645** [comment]
> localhost:3000で確認すると、下記のようなエラーが出てますね。
> 
> ```
> covid19 | 
> covid19 | found in
> covid19 | 
> covid19 | ---> <Pages/cards/Card.vue> at pages/cards/_card.vue
> covid19 |        <Nuxt>
> covid19 |          <VApp>
> covid19 |            <Layouts/default.vue> at layouts/default.vue
> covid19 |              <Root>
> covid19 | 
> ```
> 
> ![2020-11-29_17-21](https://user-images.githubusercontent.com/13390370/100536953-83d92b00-3267-11eb-86cf-8a8f0a02f9c9.png)
> 
> _card.vue の102行目
> ![2020-11-29_17-24](https://user-images.githubusercontent.com/13390370/100536980-c864c680-3267-11eb-9790-4c6debd9f9f8.png)
> 
> data.json　で　inspection_persons.date が読めない？
> それにしても、devサイトでは何故表示される？

多分`updatedAt = Data.main_summary.date`じゃないとダメな気がします。

この辺、なぜか通ってしまう理由がわからないもので、逆に変えるといろいろと問題がある気がします。と思ったら他言語化回りの警告メッセージも気になりますね。
自分もまだ追えてないので何とも言えません。メトロ版はどうやら出ていないようなので、履歴での修正のされ方を追いたいですね。

**Comment by aktnk** [comment]
> 多分updatedAt = Data.main_summary.dateじゃないとダメな気がします。

このDataは、data.jsonを取り込んだものですので、main_summaryはあっても、
その中にdateが存在しないため、updatedAt = Data.main_summary.dateとすると、
”dateがない”エラーとなってしまうと思います。
```
	"lastUpdate": "2020/12/04 19:30",
	"main_summary": {
		"attr": "検査実施人数",
		"value": 0,
		"children": [
			{
				"attr": "陽性患者数",
				"value": 1827,
				"children": [
					{
						"attr": "入院中",
						"value": 189,
						"children": [
							{
								"attr": "軽症・中等症",
								"value": 179
							},
							{
								"attr": "重症",
								"value": 10
							}
						]
					},
					{
						"attr": "宿泊療養",
						"value": 58
					},
					{
						"attr": "入院・療養等調整中",
						"value": 323
					},
					{
						"attr": "死亡",
						"value": 14
					},
					{
						"attr": "退院",
						"value": 1243
					}
				]
			}
		]
	}
```

尚、今回の修正で、Data.patients.dateとしたのは、
検査陽性者の状況の各数値は、data.json内のpatientsデータを集計して算出していたためで、
実際に「検査陽性者の状況」を生成している下記実装と合わせています。
https://github.com/hiroyuki-ichikawa/covid19/blob/87ac95b3f0dec16d9fa7990d5650d3be1384bc97/components/cards/ConfirmedCasesDetailsCard.vue#L4-L6

しかし、先日「検査陽性者の状況」の集計値はオープンデータとして提供されるようになったため、
そのデータが公開された日を、main_summary内にdateとして追加する形に変更するのであれば、
Data.main_summary.dateとして生きてくると思います。

**Comment by hrsano645** [comment]
> > 多分updatedAt = Data.main_summary.dateじゃないとダメな気がします。
> 
> このDataは、data.jsonを取り込んだものですので、main_summaryはあっても、
> その中にdateが存在しないため、updatedAt = Data.main_summary.dateとすると、
> ”dateがない”エラーとなってしまうと思います。

> 尚、今回の修正で、Data.patients.dateとしたのは、
> 検査陽性者の状況の各数値は、data.json内のpatientsデータを集計して算出していたためで、
> 実際に「検査陽性者の状況」を生成している下記実装と合わせています。
> https://github.com/hiroyuki-ichikawa/covid19/blob/87ac95b3f0dec16d9fa7990d5650d3be1384bc97/components/cards/ConfirmedCasesDetailsCard.vue#L4-L6

これは勘違いしてました。 @aktnk さんの解説で納得です。
メトロ版でも同じような修正入ってました。
https://github.com/tokyo-metropolitan-gov/covid19/pull/1954

> しかし、先日「検査陽性者の状況」の集計値はオープンデータとして提供されるようになったため、
> そのデータが公開された日を、main_summary内にdateとして追加する形に変更するのであれば、
> Data.main_summary.dateとして生きてくると思います。

「検査陽性者の状況」（集計値）のmain_summary.dateは、そういえば存在してなかったので新設してもいいかなと思ってます。（キーを増やすから互換性は問題ないかな？）
「検査陽性者の状況」カードの今の実装だと「陽性患者の属性」であるpatients.dateと実質同じにしてしまってますが、言及通り、集計値と属性情報を分けて更新間隔も違うので、正しい更新日時を用意したほうがわかりやすそうですね。

**Comment by hrsano645** [comment]
main_summary.dateを作るコードを生成スクリプト側でやろうと思います。issue作成しますね～

**Comment by aktnk** [comment]
よろしくお願いします。
