### ISSUE TITLE
GitHub Actionsのワークフローupdate/update master内のdeployタスクでエラーが発生している

### ISSUE THREAD

**Issue by aktnk** [aktnk/covid19#49]
## 起こっている問題 / The Problem
- deployタスク内のRun yarn run generate:dev --fail-on-page-error実行時のログを見ると、
[error] [nuxt-purgecss] Webpack mode only works with build.extractCSS set to *true*. Either extract your CSS or use 'postcss' mode　が1回
[error] [Vue warn]: Error in data(): "TypeError: Cannot read property 'date' of undefined"　が12回
発生している。
https://github.com/hiroyuki-ichikawa/covid19/runs/1503372896?check_suite_focus=true
- 上記エラーは、developmentブランチ＆masterブランチのupdate時に発生している。

## スクリーンショット / Screenshot

- update at development branch 
![image](https://user-images.githubusercontent.com/13390370/101273963-90b4cc00-37dd-11eb-9034-7e5c8e86b45f.png)
- update at master branch
![image](https://user-images.githubusercontent.com/13390370/101274046-27818880-37de-11eb-8848-ca393993e977.png)

## 期待する見せ方・挙動 / Expected Behavior
- エラーが発生せず、実行が終了すること。

## 起こっている問題の再現手段 / Steps to Reproduce
1. developmentブランチ/masterブランチに変更を登録する

## 動作環境・ブラウザ / Environment
- GitHub Actionsの実行のため、クライアント環境は無関係

**Comment by hrsano645** [comment]
> [error] [Vue warn]: Error in data(): "TypeError: Cannot read property 'date' of undefined"　が12回
発生している。

このエラーは #50 側に分けてみます。
もう一つのエラーはここで扱いましょうか。

**Comment by hrsano645** [comment]
> [error] [nuxt-purgecss] Webpack mode only works with build.extractCSS set to true. Either extract your CSS or use 'postcss' mode　が1回

[Nuxt.js | PurgeCSS](https://purgecss.com/guides/nuxt.html)というビルド時に、使っていないCSSのスタイル情報を除去するツールだそうです。

参考: https://coliss.com/articles/build-websites/operation/css/how-to-remove-unused-css.html

このエラーは、単純にオプション定義する必要があるらしくて、nuxt.config.tsに記載すればよいらしいです。(webpackモードの時には、build.extractCSSオプションをtrueにする）

https://purgecss.com/guides/nuxt.html#properties-in-depth

メトロ側での修正も入ってました。同じようにすればよさそう

https://github.com/tokyo-metropolitan-gov/covid19/pull/725
https://github.com/tokyo-metropolitan-gov/covid19/pull/725/commits/53f1b6ecdd3f3fcf8b802fae71066b2d75768c73

**Comment by aktnk** [comment]
メトロ版でもありましたか！
私も探しましたが、見つけられませんでした。
内容確認します。

**Comment by aktnk** [comment]
covid19-testにて`extractCSS: true`の変更を行い、deploy actionを検証しました。
https://github.com/aktnk/covid19-test/commit/95e91ae19bf0deaca43dd531ab28232952f54daf
https://github.com/aktnk/covid19-test/runs/1537604434
- 下記のようにerrorが発生しなくなったことを確認しました。
![image](https://user-images.githubusercontent.com/13390370/101913626-927bf680-3c06-11eb-8801-9a75f171e04e.png)
なお、同時に、docker-compose up --build時にエラーが発生していないこと、コンテンツも問題なく表示されることを確認しました。
⇒PRします。
