### ISSUE TITLE
headタグ内のmetaタグにtwitter:site,twitter:creatorに@tokyo_bosaiが指定されている

### ISSUE THREAD

**Issue by aktnk** [aktnk/covid19#52]
## 起こっている問題 / The Problem
- 静岡県防災のtwitterアカウント"@shizuoka_bousai"を使って指定すべき箇所が"＠tokyo_bousai"となっている

## スクリーンショット / Screenshot

- 現状のhttps://stopcovid19.code4numazu.org/ の該当箇所
![image](https://user-images.githubusercontent.com/13390370/101916796-c5c08480-3c0a-11eb-9434-9325aa600d5c.png)

## 期待する見せ方・挙動 / Expected Behavior
- twitter:site,twitter:creatorが"@shizuoka_bousai”となっている

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://stopcovid19.code4numazu.org/ にアクセスする
2. ソースコードを表示する 

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
この辺ですね。nuxt.config.ts修正でよさそう。

https://github.com/hiroyuki-ichikawa/covid19/blob/development/nuxt.config.ts#L36

**Comment by aktnk** [comment]
下記の記載があることに初めて気が付いたのですが、Twitter以外にも修正が必要そうです。
[派生版をつくるときにまずやることリスト](https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?both#%E6%B4%BE%E7%94%9F%E7%89%88%E3%82%92%E4%BD%9C%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AB%E3%81%BE%E3%81%9A%E3%80%81%E3%82%84%E3%82%8B%E3%81%93%E3%81%A8%E3%83%AA%E3%82%B9%E3%83%88)

**Comment by aktnk** [comment]
メトロ版とheadタグ内の情報を比較すると、下記についても修正が必要そうです。
- <link data-n-head="ssr" rel="canonical" href="https://stopcovid19-shizuoka-dev.netlify.com/">

**Comment by hrsano645** [comment]
> メトロ版とheadタグ内の情報を比較すると、下記についても修正が必要そうです。
> 
> * `<link data-n-head="ssr" rel="canonical" href="https://stopcovid19-shizuoka-dev.netlify.com/">` はリンク先が間違っている
> * `<link data-n-head="ssr" rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css">`は不要では？



> 修正が必要な場所は　@hrsano645 さんが先に指摘された
> 
> * https://github.com/hiroyuki-ichikawa/covid19/blob/development/nuxt.config.ts
> 
> と、下記辺りと思われます。
> 
> * https://github.com/hiroyuki-ichikawa/covid19/blob/development/layouts/default.vue

了解です。この辺まとめてタグの整理としてPR立てておきます。

**Comment by hrsano645** [comment]
PR作りました。og:urlの修正も通常だと必要なはずなので盛り込んでます。

**Comment by hrsano645** [comment]
もう終了済みだったので終了しておきます。
