### ISSUE TITLE
「検査実施件数」の表示項目の変更（静岡県からの依頼）

### ISSUE THREAD

**Issue by jandknagaya** [aktnk/covid19#53]
## 起こっている問題 / The Problem
- オープンデータの集計内容の変更（検査件数の集計⇒検査人数の集計）にに伴う表記の変更

## スクリーンショット / Screenshot
変更依頼内容（Slackより）
https://codefornumazu.slack.com/archives/C011YSQPQCA/p1608857722011100

## 期待する見せ方・挙動 / Expected Behavior
- 変更内容

旧：検査実施件数　
新：検体採取実施人数

旧：（注）検査結果の判定日を基準とする
新：（注）検体を採取した日を基準とする

旧：（注）同一の対象者について複数の検体を検査する場合あり
新：（注）同一の対象者について複数の検体を検査する場合あり（11月30日までは件数、12月1日以降は人数を集計）

旧：地方衛生研究所が行った検査件数
新：保健所が行政検査として行った検体採取人数

旧：医療機関等が行った検査件数
新：医療機関などが行政検査として行った検体採取人数

（棒グラフのマウスオーバー時に表示される説明）
旧：地方衛生研究所　
新：保健所　　　
※12月1日以降は　旧：999件　⇒　新：999人

- 県担当者の依頼時のメモ
![日別](https://user-images.githubusercontent.com/65159906/103138076-3ccd4100-4712-11eb-935b-8c9af2956384.png)

![累計](https://user-images.githubusercontent.com/65159906/103138078-435bb880-4712-11eb-8cf1-d78d0ab5e138.png)

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトを表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by aktnk** [comment]
変更要望なので、bug -> enhancement にしました。
