### ISSUE TITLE
日付表示に西暦を追加する

### ISSUE THREAD

**Issue by aktnk** [aktnk/covid19#60]
## 改善詳細 / Details of Improvement
- 「陽性患者の属性」の日付表示に西暦を追加する
- 「陽性患者数」の日付表示に西暦を追加する
- 「新型コロナ受診相談窓口相談件数」の日付表示に西暦を追加する
- 「検査（検体採取）実施人数」の日付表示に西暦を追加する

## スクリーンショット / Screenshot

- 「陽性患者の属性」
![image](https://user-images.githubusercontent.com/13390370/104113764-0dd4e300-5340-11eb-9558-ab99dc2373eb.png)
- 「陽性患者数」
![image](https://user-images.githubusercontent.com/13390370/104113777-45438f80-5340-11eb-94dd-99958f4b4296.png)
- 「新型コロナ受信相談窓口相談件数」
![image](https://user-images.githubusercontent.com/13390370/104113792-7b810f00-5340-11eb-82da-b60a6bd87039.png)
- 「検査（検体採取）実施人数」
![image](https://user-images.githubusercontent.com/13390370/104113821-bd11ba00-5340-11eb-8f92-2a2432626ca5.png)

## 期待する見せ方・挙動 / Expected behavior
- 陽性患者の属性（東京都を例に）
![image](https://user-images.githubusercontent.com/13390370/104113619-ce59c700-533e-11eb-86e6-8227e3040de1.png)
- 検査実施件数（東京都を例に）
![image](https://user-images.githubusercontent.com/13390370/104113718-87b89c80-533f-11eb-8f0c-3cca6913dec7.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
そろそろ気になりますね。メトロ側のissue上げておきます。

- https://github.com/tokyo-metropolitan-gov/covid19/issues/5750
- https://github.com/tokyo-metropolitan-gov/covid19/issues/5790
