### ISSUE TITLE
OGP Builderの動作が失敗している

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#67]
## 起こっている問題 / The Problem
- 現在のバージョンだとOGP Builderが止まってしまってる
  - https://github.com/hiroyuki-ichikawa/covid19/runs/1783961754?check_suite_focus=true
- 原因はまだよくわかってないです
  - スクリーンショット撮影時のサイトアクセスでTimeoutしてるので、途中で動かない個別カード表示のものとか、表示自体が遅くて問題になっている可能性があります。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/23502/106221746-89c89980-6221-11eb-91db-7ab40bcb5d0c.png)

## 期待する見せ方・挙動 / Expected Behavior
- OGP Builderを動作させてOGPで利用されるカードの画像を生成できるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://github.com/hiroyuki-ichikawa/covid19/runs/1783961754?check_suite_focus=true にて再現

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by hrsano645** [comment]
静岡県側も対応したいと思っているので、調査してみます。

**Comment by hrsano645** [comment]
https://github.com/aktnk/covid19/issues/76 より派生して調査中

最近同様の問題が起きていない（富士市側でも起きていない）ので調査してみてますが、仮説として

- Actionsのランナーホスト側のアップデートが入って、問題が起こりに行くくなった 
  - chromeはランナーホスト側のアップデートで影響される
  - seleniumは `.github\workflows\ogp_builder.yml` で `pip3 install selenium` で常に最新版がインストールされる
    Actionsのキャッシュ機能はどうやらnode側のみらしい -> https://github.com/hiroyuki-ichikawa/covid19/blob/development/.github/workflows/ogp_builder.yml#L34
- Actionsのランナー自体の性能が良くなってる

**Comment by hrsano645** [comment]
このissueのエラー自体は、すでにエラーとしては起きていないようです

- 2021/2/23頃のワークフロー結果では、該当のジョブでエラーが起きているので失敗している可能性あり
  - https://github.com/hiroyuki-ichikawa/covid19/runs/1961067911?check_suite_focus=true 
  - ![image](https://user-images.githubusercontent.com/23502/148667309-ea87b8cb-4003-4480-9506-0f997ef569be.png)
- 2/24以降は正常に実行されている

2/24周辺の問題だと思ったので、さらに調べたところmasterへ以下のPRがありました

- https://github.com/hiroyuki-ichikawa/covid19/pull/153

developmentでもmasterへmergeされた3つのPR変更が入っていて、この三つのどれかが影響したようにも見えました。
ですが、富士市版では同様のmergeは無く、同じタイミングでワークフローが成功していたので、コードの変更から改善したわけではなさそうです。

そうなると、やはりランナーホストのアップデートと思われます。

（seleniumのバージョンはこの期間はアップデートなかったので除外です -> https://pypi.org/project/selenium/#history）


2021/2/24周辺のmacOSランナーのアップデートを見ると 2/20にありました

https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210220.1

関係してそうなアップデートの変更を見ます

- chrome: https://github.com/actions/virtual-environments/commit/238c623deff939b5c00bf2fe94b6d44fdb89a5cd?diff=split#diff-7a1606bd717fc0cf55f9419157117d9ca306f91bd2fdfc294720687d7be1b2c7L117
- python: https://github.com/actions/virtual-environments/commit/238c623deff939b5c00bf2fe94b6d44fdb89a5cd?diff=split#diff-7a1606bd717fc0cf55f9419157117d9ca306f91bd2fdfc294720687d7be1b2c7L151
- node: アップデート無し

nodeはogp_screenshot.pyの撮影時に直接影響はないので無視でよさそう。chromeとpythonのアップデートがあるのでそれぞれのアップデートのログを載せておきます

- chrome: https://chromium.googlesource.com/chromium/src/+log/88.0.4324.150..88.0.4324.182?pretty=fuller&n=10000
- python:
  - 3.6（多分実行時はこちらが使われているはず）: https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-13-final 
  - 3.7: https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-10-final
  - 3.8: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-8-final

---

とここまで調べた限りで、再現するには時間が必要そうです。現状起きてない問題で対処しづらいこともあるので、ここまでの調整で止めておきます…

**Comment by hrsano645** [comment]
現在のchrome v96でcardのレンダリング時間を見た結果です。

https://stopcovid19.code4numazu.org/cards/number-of-reports-to-covid19-consultation-desk/

![image](https://user-images.githubusercontent.com/23502/148668314-97e86336-2fe0-45cf-8fbb-d5d8c47d2ba6.png)

富士市版側で調査していた時の結果も載せておきます

https://github.com/hiroyuki-ichikawa/fujicity_covid19/issues/28#issuecomment-773334558

![fuji test](https://user-images.githubusercontent.com/23502/106903825-d63e3880-673d-11eb-9c82-d6fec2e3138b.png)

当時はcardを表示した段階で読み込みが終わらない状況でしたが、今は1秒足らずで読み込み終了してます。

**Comment by aktnk** [comment]
下記の修正により、OGP builderの生成にかかる時間が削減され、現状Timeoutは発生しなくなったため、closeとします。

**（補足）**
https://github.com/aktnk/covid19/issues/78 の対策として実施た下記の修正により改善
- https://github.com/hiroyuki-ichikawa/covid19/pull/160
- https://github.com/hiroyuki-ichikawa/covid19/pull/161
