### ISSUE TITLE
対策サイトの「新型コロナウイルス感染症が心配なときに」のリンク先が古い

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#73]
## 起こっている問題 / The Problem
- 対策サイトにある、「新型コロナウイルス感染症が心配なときに」のリンク先が現在の厚生労働省の指針に沿っていない

> コロナ電話相談の目安「37.5℃以上の発熱が４日以上」「重症化しやすい人はかぜの症状や37.5℃以上の発熱が２日程度続く場合」といったものが、厚生労働省のほうで昨年修正されているのですが※、こちらの新型コロナウイルス感染症対策サイトではリンク先が古くなっております（「新型コロナウイルス感染症が心配なときに」をクリックすると閲覧出来ます）。
> 県公式という事もありますので、ご修正頂けないでしょうか。
> なお、自治体側など、もしご可能なら県の方にも確認を取って頂けますと助かります。
> 
> Code for ふじのくに　お問合せより

- [県の新型コロナ情報サイト](https://www.pref.shizuoka.jp/kinkyu/covid-19.html)での相談窓口の連絡先が変わっている可能性あり
  -  https://www.pref.shizuoka.jp/kinkyu/documents/hatsunetujyusincenter.pdf

## スクリーンショット / Screenshot

リンク先のサイトはこちら

https://www.pref.shizuoka.jp/kinkyu/covid-19-mosimosoudannsaki.html

![image](https://user-images.githubusercontent.com/23502/118485504-7d763700-b753-11eb-8698-290b8ad83435.png)

## 期待する見せ方・挙動 / Expected Behavior
- 相談窓口のリンクを変更する
  - PDFだけどここが望ましい？: https://www.pref.shizuoka.jp/kinkyu/documents/hatsunetujyusincenter.pdf

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by hrsano645** [comment]
厚生労働省の各県の相談センターについてのリンク先はちょっと違いました。悩みますね…

[新型コロナウイルスに関する相談・医療の情報や受診・相談センター｜厚生労働省](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19-kikokusyasessyokusya.html)

[静岡県／新型コロナウイルス感染症について](https://www.pref.shizuoka.jp/kousei/ko-420a/kansen/new-cov.html#hatsunetsutoujushinsoudancenter)

**Comment by hrsano645** [comment]
> [静岡県／新型コロナウイルス感染症について](https://www.pref.shizuoka.jp/kousei/ko-420a/kansen/new-cov.html#hatsunetsutoujushinsoudancenter)

こちらのリンクのほうが静岡市の「新型コロナなんでも相談ダイヤル」が記載されているので、そちらの方がいいかもしれません。

お問合せの意図としては、厚生労働省がすでにコロナ電話相談の目安を使っていなくて、かかりつけ医がいない場合は発熱センターへ相談になっているので、リンク先の情報源でも大丈夫そうだと考えてます。ただPDFファイルのほうが相談方法が明確になってるのもあるので、ちょっと悩ましいです。

（厚生労働省にある相談センターの静岡県リンクでの説明抜粋）

![image](https://user-images.githubusercontent.com/23502/118488722-ff1b9400-b756-11eb-808c-15ff8ca8e338.png)


（PDFファイルの説明抜粋）

![image](https://user-images.githubusercontent.com/23502/118488573-d5626d00-b756-11eb-9266-fc4a141a6705.png)

**Comment by jandknagaya** [comment]
Slack 2021.05.18 14:15 市川さんの投稿参照

静岡県よりリンク先の指定がありました。
https://www.pref.shizuoka.jp/kinkyu/documents/hatsunetujyusincenter.pdf

**Comment by hrsano645** [comment]
Merge済みなので終了します。お疲れ様でした🙌
