### ISSUE TITLE
静岡県 新型コロナウイルス感染症対策サイトのリンクがhttpとなっている

### ISSUE THREAD

**Issue by frameghostman** [aktnk/covid19#77]
## 起こっている問題 / The Problem
https://github.com/hiroyuki-ichikawa/covid19 の about からアクセスできる
静岡県 新型コロナウイルス感染症対策サイトのリンクがhttpsになっていない。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/96729917/149091999-084f8138-6f83-4426-b097-d3288f94562f.png)
![image](https://user-images.githubusercontent.com/96729917/149092410-55eb9041-111a-4684-8f8b-254f07764101.png)

## 期待する見せ方・挙動 / Expected Behavior
リンク先をhttpsへ

## 起こっている問題の再現手段 / Steps to Reproduce
リンクをクリックするのみ

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by hrsano645** [comment]
@frameghostman issueありがとうございます！
 githubプロジェクトのURLがhttpですね。 typoっぽいので修正します。

**Comment by hiroyuki-ichikawa** [comment]
修正しました。

**Comment by hrsano645** [comment]
@hiroyuki-ichikawa 修正確認済みです！

![image](https://user-images.githubusercontent.com/23502/152316405-b4346d14-316d-4652-8b4d-7b72fa4442b4.png)

@frameghostman 提案ありがとうございました！ Closeします。
